const PRODUCTS = [
  { id: 1, name: "Бургер", price: 8, category: "Еда и мелочи", emoji: "🍔", description: "Классика быстрого финансового решения.", popularity: 100, crazy: 1 },
  { id: 2, name: "Пицца", price: 18, category: "Еда и мелочи", emoji: "🍕", description: "Большая, горячая и с двойным сыром.", popularity: 98, crazy: 1 },
  { id: 3, name: "Кофе", price: 6, category: "Еда и мелочи", emoji: "☕", description: "Топливо для следующего стартапа.", popularity: 99, crazy: 1 },
  { id: 4, name: "Шаурма", price: 7, category: "Еда и мелочи", emoji: "🌯", description: "Инвестиция с чесночным соусом.", popularity: 95, crazy: 2 },
  { id: 5, name: "Подписка на музыку", price: 120, category: "Еда и мелочи", emoji: "🎵", description: "Год без рекламы и тишины.", popularity: 90, crazy: 1 },
  { id: 6, name: "Подписка на стриминг", price: 180, category: "Еда и мелочи", emoji: "🍿", description: "Все сериалы, которые некогда смотреть.", popularity: 88, crazy: 1 },
  { id: 7, name: "Игровой скин", price: 25, category: "Еда и мелочи", emoji: "🎨", description: "Выглядеть богато тоже важно.", popularity: 93, crazy: 3 },
  { id: 8, name: "Кроссовки", price: 180, category: "Еда и мелочи", emoji: "👟", description: "Для быстрых переговоров.", popularity: 83, crazy: 1 },
  { id: 9, name: "Куртка", price: 350, category: "Еда и мелочи", emoji: "🧥", description: "Практичная версия с карманами.", popularity: 66, crazy: 1 },
  { id: 10, name: "Золотой бургер", price: 5000, category: "Еда и мелочи", emoji: "✨", description: "Съедобная демонстрация плохих решений.", popularity: 70, crazy: 7 },
  { id: 11, name: "Игровая мышка", price: 120, category: "Техника", emoji: "🖱️", description: "Еще больше кнопок, еще меньше работы.", popularity: 91, crazy: 1 },
  { id: 12, name: "Механическая клавиатура", price: 220, category: "Техника", emoji: "⌨️", description: "Громко печатай важные твиты.", popularity: 89, crazy: 2 },
  { id: 13, name: "Наушники", price: 450, category: "Техника", emoji: "🎧", description: "Шумоподавление для советов директоров.", popularity: 92, crazy: 1 },
  { id: 14, name: "iPhone", price: 1400, category: "Техника", emoji: "📱", description: "Еще один прямоугольник из будущего.", popularity: 97, crazy: 1 },
  { id: 15, name: "PlayStation", price: 600, category: "Техника", emoji: "🎮", description: "Космос подождет до конца матча.", popularity: 96, crazy: 1 },
  { id: 16, name: "Xbox", price: 550, category: "Техника", emoji: "🕹️", description: "Коробка с хорошими вечерами.", popularity: 85, crazy: 1 },
  { id: 17, name: "Игровой ПК", price: 4500, category: "Техника", emoji: "🖥️", description: "С подсветкой быстрее, это наука.", popularity: 94, crazy: 2 },
  { id: 18, name: "MacBook", price: 3200, category: "Техника", emoji: "💻", description: "Для презентации следующей революции.", popularity: 95, crazy: 1 },
  { id: 19, name: "Телевизор 8K", price: 9000, category: "Техника", emoji: "📺", description: "Чтобы видеть пиксели еще реже.", popularity: 80, crazy: 2 },
  { id: 20, name: "Домашний кинотеатр", price: 45000, category: "Техника", emoji: "🎬", description: "Премьеры без чужого попкорна.", popularity: 77, crazy: 3 },
  { id: 21, name: "Топовый компьютер", price: 18000, category: "Техника", emoji: "⚡", description: "Рендерит мечты почти мгновенно.", popularity: 87, crazy: 2 },
  { id: 22, name: "VR-шлем", price: 1200, category: "Техника", emoji: "🥽", description: "Когда этой реальности уже мало.", popularity: 84, crazy: 3 },
  { id: 23, name: "Дрон", price: 2500, category: "Техника", emoji: "🚁", description: "Красивые виды и спорные посадки.", popularity: 82, crazy: 3 },
  { id: 24, name: "Профессиональная камера", price: 12000, category: "Техника", emoji: "📷", description: "Снимать запуск ракеты в 8K.", popularity: 75, crazy: 2 },
  { id: 25, name: "3D-принтер", price: 8000, category: "Техника", emoji: "🧊", description: "Печатай детали и новые проблемы.", popularity: 72, crazy: 3 },
  { id: 26, name: "Домашний робот", price: 90000, category: "Техника", emoji: "🤖", description: "Не спорит о графике уборки.", popularity: 86, crazy: 5 },
  { id: 27, name: "Робособака", price: 150000, category: "Техника", emoji: "🐕", description: "Не просит гулять, просит зарядку.", popularity: 81, crazy: 6 },
  { id: 28, name: "Серверная стойка", price: 250000, category: "Техника", emoji: "🗄️", description: "Личный интернет в шкафу.", popularity: 64, crazy: 4 },
  { id: 29, name: "Суперкомпьютер", price: 200000000, category: "Техника", emoji: "🧠", description: "Посчитает, зачем ты его купил.", popularity: 69, crazy: 7 },
  { id: 30, name: "Дата-центр", price: 1200000000, category: "Техника", emoji: "🏢", description: "Очень много вентиляторов и данных.", popularity: 61, crazy: 7 },
  { id: 31, name: "Завод по производству чипов", price: 18000000000, category: "Техника", emoji: "🔬", description: "Кремний, чистые комнаты и амбиции.", popularity: 58, crazy: 8 },
  { id: 32, name: "Лаборатория искусственного интеллекта", price: 5000000000, category: "Техника", emoji: "🧬", description: "Исследует вопрос: что купить дальше?", popularity: 92, crazy: 8 },
  { id: 33, name: "Электросамокат", price: 900, category: "Транспорт", emoji: "🛴", description: "Почти Tesla, только стоя.", popularity: 84, crazy: 2 },
  { id: 34, name: "Велосипед", price: 2500, category: "Транспорт", emoji: "🚲", description: "Нулевые выбросы, живой двигатель.", popularity: 74, crazy: 1 },
  { id: 35, name: "Мотоцикл", price: 25000, category: "Транспорт", emoji: "🏍️", description: "Быстро, громко и без автопилота.", popularity: 78, crazy: 3 },
  { id: 36, name: "Tesla Model 3", price: 50000, category: "Транспорт", emoji: "🚗", description: "Электрический народный выбор.", popularity: 100, crazy: 2 },
  { id: 37, name: "Tesla Model S Plaid", price: 130000, category: "Транспорт", emoji: "🏎️", description: "Разгоняется быстрее решений совета.", popularity: 98, crazy: 4 },
  { id: 38, name: "Cybertruck", price: 110000, category: "Транспорт", emoji: "🔺", description: "Пикап, нарисованный одной линейкой.", popularity: 99, crazy: 6 },
  { id: 39, name: "Lamborghini", price: 350000, category: "Транспорт", emoji: "💛", description: "Практичность вышла из чата.", popularity: 94, crazy: 4 },
  { id: 40, name: "Ferrari", price: 450000, category: "Транспорт", emoji: "🏁", description: "Красная финансовая скорость.", popularity: 95, crazy: 4 },
  { id: 41, name: "Rolls-Royce", price: 600000, category: "Транспорт", emoji: "🎩", description: "Тишина с очень дорогим салоном.", popularity: 83, crazy: 5 },
  { id: 42, name: "Bugatti", price: 4000000, category: "Транспорт", emoji: "💨", description: "Чтобы опаздывать очень дорого.", popularity: 92, crazy: 6 },
  { id: 43, name: "Личный автобус", price: 800000, category: "Транспорт", emoji: "🚌", description: "Для всей команды мемов.", popularity: 55, crazy: 5 },
  { id: 44, name: "Вертолет", price: 12000000, category: "Транспорт", emoji: "🚁", description: "Пробки существуют для других.", popularity: 79, crazy: 6 },
  { id: 45, name: "Частный самолет", price: 75000000, category: "Транспорт", emoji: "✈️", description: "Переговорная на высоте 12 км.", popularity: 88, crazy: 7 },
  { id: 46, name: "Яхта", price: 120000000, category: "Транспорт", emoji: "🛥️", description: "Море, палуба и счета за топливо.", popularity: 86, crazy: 7 },
  { id: 47, name: "Суперъяхта", price: 600000000, category: "Транспорт", emoji: "🚢", description: "Плавучий город с полотенцами.", popularity: 90, crazy: 8 },
  { id: 48, name: "Подводная лодка", price: 900000000, category: "Транспорт", emoji: "🌊", description: "Совещания глубже обычного.", popularity: 65, crazy: 9 },
  { id: 49, name: "Поезд", price: 180000000, category: "Транспорт", emoji: "🚆", description: "Собственный маршрут без пересадок.", popularity: 60, crazy: 7 },
  { id: 50, name: "Гоночная команда", price: 900000000, category: "Транспорт", emoji: "🏆", description: "Очень быстрый способ жечь бюджет.", popularity: 82, crazy: 8 },
  { id: 51, name: "Авиакомпания", price: 12000000000, category: "Транспорт", emoji: "🛫", description: "Теперь задержка рейса тоже твоя.", popularity: 71, crazy: 8 },
  { id: 52, name: "Квартира", price: 300000, category: "Недвижимость", emoji: "🏠", description: "Уютные квадратные метры.", popularity: 92, crazy: 1 },
  { id: 53, name: "Дом", price: 900000, category: "Недвижимость", emoji: "🏡", description: "С гаражом для пары Tesla.", popularity: 95, crazy: 2 },
  { id: 54, name: "Особняк", price: 25000000, category: "Недвижимость", emoji: "🏛️", description: "Комнаты, в которых легко потеряться.", popularity: 89, crazy: 5 },
  { id: 55, name: "Пентхаус", price: 45000000, category: "Недвижимость", emoji: "🌇", description: "Город выглядит дешевле сверху.", popularity: 85, crazy: 5 },
  { id: 56, name: "Замок", price: 80000000, category: "Недвижимость", emoji: "🏰", description: "Wi-Fi не везде, зато есть башни.", popularity: 80, crazy: 7 },
  { id: 57, name: "Отель", price: 150000000, category: "Недвижимость", emoji: "🏨", description: "Ты всегда почетный гость.", popularity: 73, crazy: 5 },
  { id: 58, name: "Торговый центр", price: 400000000, category: "Недвижимость", emoji: "🛍️", description: "Место, где другие тоже тратят.", popularity: 69, crazy: 6 },
  { id: 59, name: "Стадион", price: 900000000, category: "Недвижимость", emoji: "🏟️", description: "Заполни его фанатами и дронами.", popularity: 79, crazy: 7 },
  { id: 60, name: "Небоскреб", price: 1800000000, category: "Недвижимость", emoji: "🏙️", description: "Большой вертикальный офис.", popularity: 84, crazy: 7 },
  { id: 61, name: "Горнолыжный курорт", price: 2500000000, category: "Недвижимость", emoji: "🏔️", description: "Снег, подъемники и горячий шоколад.", popularity: 76, crazy: 7 },
  { id: 62, name: "Частный остров", price: 350000000, category: "Недвижимость", emoji: "🏝️", description: "Тихий режим размером с остров.", popularity: 91, crazy: 8 },
  { id: 63, name: "Городской квартал", price: 5000000000, category: "Недвижимость", emoji: "🌆", description: "Пара улиц для личной урбанистики.", popularity: 62, crazy: 8 },
  { id: 64, name: "Мини-город", price: 25000000000, category: "Недвижимость", emoji: "🌃", description: "Со светофорами, парком и амбициями.", popularity: 72, crazy: 9 },
  { id: 65, name: "Космический отель", price: 45000000000, category: "Недвижимость", emoji: "🛰️", description: "Пять звезд и невесомый завтрак.", popularity: 88, crazy: 10 },
  { id: 66, name: "Кафе", price: 250000, category: "Бизнес", emoji: "🥐", description: "Маленький бизнес с большим латте.", popularity: 80, crazy: 2 },
  { id: 67, name: "Ресторан", price: 1500000, category: "Бизнес", emoji: "🍽️", description: "Авторская кухня и важные столики.", popularity: 82, crazy: 3 },
  { id: 68, name: "Сеть ресторанов", price: 120000000, category: "Бизнес", emoji: "🥗", description: "Одинаково вкусно в ста городах.", popularity: 77, crazy: 5 },
  { id: 69, name: "Киберспортивная команда", price: 25000000, category: "Бизнес", emoji: "🎮", description: "Пять игроков и миллион тренировок.", popularity: 89, crazy: 5 },
  { id: 70, name: "Футбольный клуб", price: 1200000000, category: "Бизнес", emoji: "⚽", description: "Трансферы дороже ракет.", popularity: 96, crazy: 7 },
  { id: 71, name: "Игровая студия", price: 400000000, category: "Бизнес", emoji: "👾", description: "Сделай игру про покупку студии.", popularity: 91, crazy: 6 },
  { id: 72, name: "Киностудия", price: 3500000000, category: "Бизнес", emoji: "🎞️", description: "Сними фильм о собственном бюджете.", popularity: 81, crazy: 7 },
  { id: 73, name: "Музыкальный лейбл", price: 750000000, category: "Бизнес", emoji: "🎙️", description: "Выпускай хиты прямо с Марса.", popularity: 74, crazy: 6 },
  { id: 74, name: "Компания доставки", price: 2800000000, category: "Бизнес", emoji: "📦", description: "Доставляет даже странные идеи.", popularity: 83, crazy: 6 },
  { id: 75, name: "Стартап в сфере ИИ", price: 500000000, category: "Бизнес", emoji: "💡", description: "Пока только презентация, но красивая.", popularity: 99, crazy: 7 },
  { id: 76, name: "Компания по производству роботов", price: 8000000000, category: "Бизнес", emoji: "🦾", description: "Железные коллеги без отпусков.", popularity: 87, crazy: 8 },
  { id: 77, name: "Завод электромобилей", price: 14000000000, category: "Бизнес", emoji: "🏭", description: "Много машин и еще больше конвейеров.", popularity: 90, crazy: 8 },
  { id: 78, name: "Медиа-холдинг", price: 18000000000, category: "Бизнес", emoji: "📰", description: "Теперь новости начинаются с тебя.", popularity: 67, crazy: 8 },
  { id: 79, name: "Банк", price: 30000000000, category: "Бизнес", emoji: "🏦", description: "Покупка места, где лежат деньги.", popularity: 70, crazy: 9 },
  { id: 80, name: "Маркетплейс", price: 50000000000, category: "Бизнес", emoji: "🛒", description: "Кнопка купить для всего мира.", popularity: 86, crazy: 9 },
  { id: 81, name: "Социальная сеть", price: 44000000000, category: "Бизнес", emoji: "💬", description: "Лента, подписки и бесконечные споры.", popularity: 100, crazy: 10 },
  { id: 82, name: "Скафандр", price: 15000000, category: "Космос", emoji: "🧑‍🚀", description: "Деловой костюм для вакуума.", popularity: 90, crazy: 5 },
  { id: 83, name: "Спутник", price: 65000000, category: "Космос", emoji: "📡", description: "Связь сверху выглядит убедительнее.", popularity: 89, crazy: 6 },
  { id: 84, name: "Запуск ракеты", price: 120000000, category: "Космос", emoji: "🚀", description: "Обратный отсчет включен.", popularity: 100, crazy: 7 },
  { id: 85, name: "Лунный ровер", price: 450000000, category: "Космос", emoji: "🌕", description: "Машина для очень серых дорог.", popularity: 87, crazy: 7 },
  { id: 86, name: "Марсианский ровер", price: 2500000000, category: "Космос", emoji: "🛞", description: "Красная планета, надежные колеса.", popularity: 93, crazy: 8 },
  { id: 87, name: "Полет на Луну", price: 5000000000, category: "Космос", emoji: "🌙", description: "Командировка с лучшим видом.", popularity: 98, crazy: 9 },
  { id: 88, name: "Космическая станция", price: 100000000000, category: "Космос", emoji: "🛰️", description: "Офис с круговой орбитой.", popularity: 88, crazy: 9 },
  { id: 89, name: "База на Луне", price: 180000000000, category: "Космос", emoji: "🌘", description: "Первый район с отличным небом.", popularity: 95, crazy: 10 },
  { id: 90, name: "Флот ракет", price: 220000000000, category: "Космос", emoji: "🚀", description: "Когда одной ракеты явно недостаточно.", popularity: 96, crazy: 10 },
  { id: 91, name: "Колония на Марсе", price: 400000000000, category: "Космос", emoji: "🔴", description: "Самый амбициозный переезд в истории.", popularity: 100, crazy: 10 },
  { id: 92, name: "Космический лифт", price: 650000000000, category: "Космос", emoji: "🛗", description: "Следующий этаж: орбита.", popularity: 92, crazy: 10 },
  { id: 93, name: "Терраформирование Марса", price: 800000000000, category: "Космос", emoji: "🌍", description: "Ремонт планетарного масштаба.", popularity: 99, crazy: 10 },
  { id: 94, name: "Золотой унитаз", price: 5000000, category: "Безумные покупки", emoji: "🚽", description: "Сантехника финансового успеха.", popularity: 82, crazy: 9 },
  { id: 95, name: "Армия роботов-официантов", price: 350000000, category: "Безумные покупки", emoji: "🤵", description: "Тысяча роботов и ни одного чаевого.", popularity: 85, crazy: 9 },
  { id: 96, name: "Гигантская статуя Илона", price: 900000000, category: "Безумные покупки", emoji: "🗿", description: "Скромность высотой в 80 метров.", popularity: 92, crazy: 10 },
  { id: 97, name: "Личная трасса Формулы-1", price: 1800000000, category: "Безумные покупки", emoji: "🏎️", description: "Заезд начинается у дома.", popularity: 91, crazy: 9 },
  { id: 98, name: "Самый большой фейерверк в истории", price: 2500000000, category: "Безумные покупки", emoji: "🎆", description: "Несколько секунд очень яркой экономики.", popularity: 94, crazy: 10 },
  { id: 99, name: "Личный вулкан", price: 7000000000, category: "Безумные покупки", emoji: "🌋", description: "Отопление иногда выходит из-под контроля.", popularity: 79, crazy: 10 },
  { id: 100, name: "Пульт управления мемами", price: 12000000000, category: "Безумные покупки", emoji: "📺", description: "Запускает тренды одной кнопкой.", popularity: 100, crazy: 10 },
  { id: 101, name: "Самый дорогой мем в интернете", price: 18000000000, category: "Безумные покупки", emoji: "😂", description: "Смешно ровно до просмотра счета.", popularity: 96, crazy: 10 },
  { id: 102, name: "Искусственный остров в форме X", price: 28000000000, category: "Безумные покупки", emoji: "❎", description: "Видно из космоса и бухгалтерии.", popularity: 93, crazy: 10 },
  { id: 103, name: "Покупка маленькой страны в игре", price: 50000000000, category: "Безумные покупки", emoji: "🏳️", description: "Только виртуально, зато с флагом.", popularity: 88, crazy: 10 },
  { id: 104, name: "Город будущего", price: 120000000000, category: "Безумные покупки", emoji: "🌐", description: "Без пробок, но с неоном.", popularity: 97, crazy: 10 },
  { id: 105, name: "Машина времени", price: 250000000000, category: "Безумные покупки", emoji: "⏳", description: "Вернись и купи биткоин. Наверное.", popularity: 100, crazy: 10 },
  { id: 106, name: "Портал на Марс", price: 500000000000, category: "Безумные покупки", emoji: "🌀", description: "Ракеты теперь можно продать.", popularity: 100, crazy: 10 },
  { id: 107, name: "Личная планета", price: 849999999999, category: "Безумные покупки", emoji: "🪐", description: "Почти идеальный способ потратить все.", popularity: 100, crazy: 10 }
];

const CATEGORIES = ["Все", "Еда и мелочи", "Техника", "Транспорт", "Недвижимость", "Бизнес", "Космос", "Безумные покупки"];
